### ISSUE TITLE
Fix expiration calculations

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/mpx-php#11]
MPX returns a relative time for a token instead of an absolute time. That means that Tokens need to store the date they were created, otherwise we can't properly calculate when a token should be expired from the cache.

**Comment by davereid** [comment]
That's what we do in https://github.com/Lullabot/mpx-php/blob/master/src/Token.php#L33?

**Comment by deviantintegral** [comment]
Yes, indeed. I was getting turned around by https://github.com/Lullabot/mpx-php/blob/master/src/User.php#L105 as both `expiresAt` and `expiresAfter` have the same doc comment in the PSR interface. I'm going to file an upstream PR.
