### ISSUE TITLE
Support fetching video data based on a feed id from MPX

### ISSUE THREAD

**Issue by m4olivei** [Lullabot/mpx-php#143]
Given a MPX feed id, we need to be able to query MPX to get back a list of videos and their details that are part of the feed.

MPX docs reference: https://docs.theplatform.com/help/feeds-requesting-media-feeds

**Comment by geekygnr** [comment]
Based on notes from @deviantintegral and @m4olivei:

- https://docs.theplatform.com/help/feeds-client-cjson at a glance looks identical to https://docs.theplatform.com/help/wsf-cjson-format#tp-toc10
- This suggests the something similar to https://github.com/Lullabot/mpx-php/blob/3107771b8f14cffe3f8f1f319d954e0add17b4e6/src/DataService/DataObjectFactory.php#L194-L208 could be achieved
- It may even be worth it to create an interface that both FeedsConfig and DataObjectFactory could share an interface requiring the selectRequest function to be implemented

**Comment by geekygnr** [comment]
After having a long talk with @deviantintegral:

This API does not follow the Data Service pattern that other items like Media do.

On the current timeline we can not put the effort into building a new set of objects to query, digest and properly return this information.

As such a temporary solution will have to be implemented upstream and this issue will be removed from pre-beta

**Comment by m4olivei** [comment]
Closing for now.
