### ISSUE TITLE
Tag 1.0.0

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/mpx-php#163]
I've pushed up a 1.0.0-rc1 tag. If there's no reported issues that block a 1.0.0 release I will tag that in one week.

/cc @m4olivei @juampynr.

**Comment by deviantintegral** [comment]
Tagged! 🎉

**Comment by salvamomo** [comment]
![flying!](https://media.giphy.com/media/14fnBD3MQslIGc/giphy.gif)
