### ISSUE TITLE
Add compatibility with Symfony ^4.4

### ISSUE THREAD

**Issue by m4olivei** [Lullabot/mpx-php#171]
[Drupal 9 requires Symfony ^4.4](https://www.drupal.org/node/3088712). We need this to be compatible so that we can use it with Drupal 9.

**Comment by deviantintegral** [comment]
What do you think about also supporting Symfony 5?

I think this may need to be a new major version _if_ we have to drop support for a prior Symfony version too.

**Comment by m4olivei** [comment]
> What do you think about also supporting Symfony 5?

As I found out working on this, unfortunately there are a couple places where we're using code deprecated in 4.x and removed in 5.x. That unfortunately means that we will won't be able to allow for all three major branches, at least that's the case with `symfony/lock` specificially. Here are the two places:

* [StoreInterface is dep in 4.x and gone in 5.x](https://github.com/Lullabot/mpx-php/blob/master/src/Service/IdentityManagement/UserSession.php#L71). I don't think there is any way around this one...
* [Factory is dep in 4.x and gone in 5.x](https://github.com/Lullabot/mpx-php/blob/master/src/Service/IdentityManagement/UserSession.php#L173). This one we could get away with technically.

**Comment by deviantintegral** [comment]
Too bad! Thanks for checking.

**Comment by m4olivei** [comment]
Resolved by https://github.com/Lullabot/mpx-php/pull/172
