### ISSUE TITLE
Extend Guzzle client or wrap around?

### ISSUE THREAD

**Issue by davereid** [Lullabot/mpx-php#3]
There are two options when creating a client object:

1. Have my class extend GuzzleHttp\Client and make calls to `$this->{method}`
2. Have my class take a GuzzleHttp\Client object as a constructor parameter and make calls to `$this->client->{method}`

I tend to prefer option 1 since it means calling code doesn't have to deal with two Client objects.

**Comment by e0ipso** [comment]
Interesting to see movement around this!

I tend to favor [composition over inheritance](https://www.lullabot.com/articles/get-a-decorator-for-your-drupal-home). But instead of `$this->client->{method}` add some nicer methods that call that for better DX.

So I lean towards 2-ish.

**Comment by davereid** [comment]
Yeah, I think the problem with decorating with regards to a Guzzle client specifically, is that is has like no setters and getters (or overridable methods) for its default config. I must pass in options like the stack handler in the GuzzleHttp\Client constructor only, it's not something where I can add in another middleware handler to an existing client (as far as I've tested and read the docs). So by extending the Guzzle Client, I'm able to modify the default options passed in via the constructor in my own object instead. I think that leans towards option 1.

**Comment by deviantintegral** [comment]
Yes, there are items that are constructor-only.

One issue is that Drupal's `\Drupal\Core\Http\ClientFactory::fromOptions()` method doesn't have a way to retrieve the default options - it _has_ to instantiate a client. So, if you want to respect proxies and other settings, you have to let Drupal do the constructing.

I've solved this in the past either with a static method (`getDefaultConfiguration(...)`) or a factory if you need more state. Does that work for us?
