### ISSUE TITLE
Return a request object instead of an array in Client

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/mpx-php#7]
`\Mpx\Client::request` currently suppresses HTTP exceptions and returns an array. The MPX documentation says we can rely on response codes, so we should use them. Also, returning a response lets callers inspect headers (like cache control).

I'm thinking it makes the most sense to keep this functionality, but as other methods so callers aren't forced into this model.

**Comment by davereid** [comment]
I believe there were issues in error handling when we attempted to rely on HTTP exceptions.

**Comment by deviantintegral** [comment]
Oy, [as soon as you use JSON they suppress HTTP errors server-side](https://docs.theplatform.com/help/wsf-handling-business-service-exceptions#tp-toc4). Normal error codes are for XML and SOAP only. There isn't even a way to turn it on.

I think we should consider casting to Guzzle exceptions (or subclasses of them) instead of `\Lullabot\Mpx\Exception\ApiException`. That will let callers behave in a normal-guzzle way, while working around the MPX limitations. Perhaps we can even make this a middleware or similar.
